version: "3.8"

services:
  db_service:
    image: mysql:8.0
    container_name: db_${GROUP_NAME}
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: password1138
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - diary_net

  app_service:
    build: ./app
    container_name: app_${GROUP_NAME}
    restart: always
    environment:
      - DB_HOST=db_service
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db_service
    networks:
      - diary_net

  nginx_service:
    image: nginx:alpine
    container_name: nginx_${GROUP_NAME}
    restart: always
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app_service
    networks:
      - diary_net

networks:
  diary_net:
    driver: bridge

volumes:
  db_data: